name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v5.3.0
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true
          # If enabled, diagnostic information will be added to the action output.
          debug: false

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/OMSExtensions_chrome.zip
            build/OMSExtensions_firefox.xpi
          tag_name: ${{ steps.semantic_version.outputs.version_tag }}
          name: Release ${{ steps.semantic_version.outputs.version_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
